# Generated by Django 5.2.8 on 2025-11-29 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_player_player_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='player_number',
        ),
        migrations.AddField(
            model_name='player',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
    ]
