# Generated by Django 5.2.8 on 2025-12-04 00:22

import colorfield.fields
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_tile_picked_by_alter_player_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='color',
            field=colorfield.fields.ColorField(default=game.models.get_random_color, image_field=None, max_length=25, samples=None),
        ),
        migrations.AlterField(
            model_name='tile',
            name='value',
            field=models.CharField(default='☐', max_length=1, validators=[game.models.validate_tile_value]),
        ),
    ]
