# Generated by Django 5.2.8 on 2025-12-04 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_alter_player_color_alter_tile_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='player_number',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
